language: csharp
solution: VSharp.sln

env:
  - VSHARPMODE=smart
  - VSHARPMODE=never

install:
  - nuget restore VSharp.sln
  - nuget install NUnit.Console -Version 3.10.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release VSharp.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./VSharp.Test/bin/Release/VSharp.Test.dll
