image: Visual Studio 2017

environment:
  matrix:
    - VSHARPMODE: smart
    - VSHARPMODE: never

before_build:
  - nuget restore

configuration: Release

test_script:
  - nunit3-console VSharp.Test\bin\Release\VSharp.Test.dll --x86 --result=myresults.xml;format=AppVeyor
